apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/grafana/intro-to-mltp/refs/heads/main/k8s/mythical/mythical-beasts-deployment.yaml
  - https://raw.githubusercontent.com/grafana/intro-to-mltp/refs/heads/main/k8s/mythical/mythical-beasts-persistentvolumeclaim.yaml
  - https://raw.githubusercontent.com/grafana/intro-to-mltp/refs/heads/main/k8s/mythical/mythical-beasts-service.yaml

patches:
  - path: patch.yaml
