---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mythical-requester
spec:
  template:
    spec:
      containers:
        - name: mythical-requester
          env:
            - name: TRACING_COLLECTOR_HOST
              value: alloy.alloy.svc
            - name: AUTHUSER
              value: grafanaopsuser
            - name: AUTHPASSWORD
              value: supersecret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mythical-server
spec:
  template:
    spec:
      containers:
        - name: mythical-server
          env:
            - name: TRACING_COLLECTOR_HOST
              value: alloy.alloy.svc
            - name: AUTHUSER
              value: grafanaopsuser
            - name: AUTHPASSWORD
              value: supersecret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mythical-recorder
spec:
  template:
    spec:
      containers:
        - env:
            - name: TRACING_COLLECTOR_HOST
              value: alloy.alloy.svc
          name: mythical-recorder
