replicas: 2

tempo:
  multitenancyEnabled: true
  metricsGenerator:
    enabled: true
    storage:
      remote_write:
        - url: http://mimir-gateway.mimir.svc/api/v1/push
          send_exemplars: true
  overrides:
    defaults:
      metrics_generator:
        processors:
          - service-graphs
          - span-metrics
          - local-blocks
  # storage:
  #   trace:
  #     backend: s3
  #     s3:
  #       access_key: "grafana-tempo"
  #       secret_key: "supersecret"
  #       bucket: "tempo-traces"
  #       endpoint: "tempo-minio:9000"
  #       insecure: true

serviceMonitor:
  enabled: true
#
# tempoQuery:
#   enabled: true
