replicas: 2

tempo:
  multitenancyEnabled: true
  storage:
    trace:
      backend: s3
      s3:
        bucket: tempo-traces
        endpoint: minio.minio.svc:9000
        insecure: true
        access_key: sandbox
        secret_key: supersecret

  metricsGenerator:
    enabled: true
    storage:
      remote_write:
        - url: http://mimir-gateway.mimir.svc/api/v1/push
          send_exemplars: true

  overrides:
    defaults:
      metrics_generator:
        processors:
          - service-graphs
          - span-metrics
          - local-blocks

serviceMonitor:
  enabled: true
#
# tempoQuery:
#   enabled: true
