{{/* -*-mode: k8s-helm-*- */}}
{{- $currentScope := . }}
{{- range $path, $_ :=  .Files.Glob  "generated/*/alerts.yaml" }}
{{- with $currentScope }}
{{- $name := dir $path | base | printf "%s-alert" }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "monitoring-mixin.fullname" . }}-{{ $name }}
  labels:
    {{- include "monitoring-mixin.labels" . | nindent 4 }}
spec:
  {{- .Files.Get $path | nindent 2 }}
{{- end }}
{{- end }}
