{{/* -*-mode: k8s-helm-*- */}}
{{- $currentScope := . }}
{{- range $path, $_ :=  .Files.Glob  "generated/*/rules.yaml" }}
{{- with $currentScope }}
{{- $name := dir $path | base | printf "%s-rule" }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "monitoring-mixin.fullname" . }}-{{ $name }}
  annotations:
    {{- with .Values.rule.annotations }}{{- toYaml . | nindent 4 }}{{- end }}
  labels:
    {{- include "monitoring-mixin.labels" . | nindent 4 }}
    {{- with .Values.rule.labels }}{{- toYaml . | nindent 4 }}{{- end }}
spec:
  {{- .Files.Get $path | nindent 2 }}
{{- end }}
{{- end }}
